name: Test Action
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install BuildBear's Foundry Fork
        run: |
          curl -L https://raw.githubusercontent.com/BuildBearLabs/foundry/master/foundryup/install | bash
        shell: bash
      
      - name: Setup Foundry
        run: |
          export PATH="$HOME/.foundry/bin:$PATH"
          foundryup
        shell: bash
      
      - name: Run Forge version
        run: |
          export PATH="$HOME/.foundry/bin:$PATH"
          forge --version
        shell: bash
      
      - name: Test
        run: |
          export PATH="$HOME/.foundry/bin:$PATH"
          forge test
        shell: bash
      
      - name: test_ci
        uses: BuildBearLabs/buildbear_x_action@feat/auto-verification-test-simulation
        with: 
          network: |
            [
              {
                "chainId": 1
              }
            ]
          deploy-command: "make exe"
          buildbear-token: "a"
