name: Test Action
on: [push]
env:
  BUILDBEAR_BASE_URL: "https://api.dev.buildbear.io"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Clone Foundry repository
        run: |
          git clone https://github.com/BuildBearLabs/foundry.git
        shell: bash
      
      - name: Build Foundry from source
        run: |
          cd foundry
          cargo build
          mkdir -p $HOME/.config/.foundry/bin
          cp target/debug/forge $HOME/.config/.foundry/bin/
          cp target/debug/cast $HOME/.config/.foundry/bin/
          cp target/debug/anvil $HOME/.config/.foundry/bin/
          cp target/debug/chisel $HOME/.config/.foundry/bin/
          echo "PATH=$HOME/.config/.foundry/bin:$PATH" >> $GITHUB_ENV
        shell: bash
      
      - name: Run Forge version
        run: forge --version
      - name: make bbOut dir
        run: mkdir bbOut 
        shell: bash
      
      - name: Test
        run: forge test
      
      - name: test_ci
        uses: BuildBearLabs/buildbear_x_action@feat/auto-verification-test-simulation
        with: 
          network: |
            [
              {
                "chainId": 1
              }
            ]
          deploy-command: "make exe"
          buildbear-token: "a"
